config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :combatants do
		patch :update_turn, on: :member
	end

  root :to => redirect('/combatants')

  get '/combatants' => 'combatants#index'
  get 'combatants/new' => 'combatants#new'
  post 'combatants' => 'combatants#create'
  delete 'combatants' => 'combatants#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combatant.rb
class Combatant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/combatants_controller.rb
class CombatantsController < ApplicationController


	def index
		@combatants = Combatant.all.order(:initiative).reverse
		maxInitId = 0
		maxInit = 0

		@combatants.each_with_index do |combatant, index|
			combatant.update(:turn_id => index)
		end

		@combatants.each do |combatant|
			if combatant.initiative > maxInit
				maxInit = combatant.initiative
				maxInitId = combatant.id
			end
		end

		#hack solution: have user enter highest init first and check box true
		# @combatants.each do |combatant|
		# 	if combatant.id == maxInitId
		# 		combatant.update(:turn => true)
		# 	end
		# end

	end

	def update_turn
		@combatant = Combatant.find(params[:id])
		@turn_id = @combatant.turn_id + 1
		@combatant.update_attribute(:turn, false)

		if Combatant.find_by(turn_id: @turn_id) != nil
			@next_combat = Combatant.find_by(turn_id: @turn_id)
			@next_combat.update_attribute(:turn, true)
			redirect_to '/combatants'
		else
			@turn_id = 0
			@next_combat = Combatant.find_by(turn_id: @turn_id)
			@next_combat.update_attribute(:turn, true)
			redirect_to '/combatants'
		end
	end
	
	def new
		@combatant = Combatant.new
	end

	def create
		@combatant = Combatant.new(combatant_params)
		if @combatant.save
			redirect_to '/combatants'
		else
			render 'new'
		end
	end

	def destroy
		Combatant.destroy(params[:id])
		redirect_to '/combatants'
	end

	private def combatant_params
		params.require(:combatant).permit(:name, :alignment, :initiative, :turn)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/combatants_helper.rb
module CombatantsHelper
end

app/views/combatants/index.html.erb
<div class='header cols'>
	Name
	<p>
	Type
	</p>
	<p>
	Initiative
	</p>
	<p>
	Turn?
	</p>
	<p>
	Kill
	</p>

</div>

<% @combatants.each do |combatant| %>
<div class='combs cols'>

		<%= combatant.name %>

	<p>
		<%= combatant.alignment %>
	</p>

	<p>
		<%= combatant.initiative %>
	</p>

	<% if combatant.turn? %>
	<p class='go-button'>
		<%= link_to "GO!", update_turn_combatant_path(combatant), method: :patch , :class => 'go-text' %>
	</p>

	<% if combatant.name.length > 7 %>

	<p>
		<%= button_to "Kill #{combatant.name[0,7]}...", combatants_path(:id => combatant.id), :method => :delete, :class => 'kill-button combs' %>
	</p>

	<% else %>

	<p>
		<%= button_to "Kill #{combatant.name}", combatants_path(:id => combatant.id), :method => :delete, :class => 'kill-button combs' %>
	</p>
	<% end %>

	<% else %>
	<p>
		Wait...
	</p>

	<% if combatant.name.length > 7 %>

	<p>
		<%= button_to "Kill #{combatant.name[0,7]}...", combatants_path(:id => combatant.id), :method => :delete, :class => 'kill-button combs' %>
	</p>

	<% else %>

	<p>
		<%= button_to "Kill #{combatant.name}", combatants_path(:id => combatant.id), :method => :delete, :class => 'kill-button combs' %>
	</p>
	
	<% end %>

	<% end %>

</div>
<% end %>

<div class='current'>
	<% @combatants.each do |combatant| %>
		<% if combatant.turn? %>
		<% if combatant.name.length > 7 %>
		It is <%= combatant.name[0,7]%>...'s turn!
		<% else %>
		It is <%= combatant.name %>'s turn!
		<% end %>
		<% end %>
	<% end %>
</div>

<div class='button'>
	<a href="/combatants/new" style="color: #ecf0f1; text-decoration: none; text-shadow: 1px 1px black;">New Combatant</a>
</div>

app/views/combatants/new.html.erb
<%= form_for(@combatant) do |f| %>
	<div>
		<%= f.label :new_combatant, :class => 'header' %><br>

		<p class = 'combs'>
		Name
		</p>
		<p>
		<%= f.text_area :name, :class => 'text' %>
		</p>

		<p class = 'combs'>
		Alignment (Player, Enemy, etc.)
		</p>
		<p>
		<%= f.text_area :alignment, :class => 'text' %>
		</p>

		<p class = 'combs'>
		Initiative
		</p>
		<p>
		<%= f.text_area :initiative, :class => 'text' %>
		</p>

		<p class = 'combs'>
		Current Turn (Check this for the highest initiative!)
		</p>
		<p>
		<%= f.check_box :turn, default: false %>
		</p>

		<p>
		<%= f.submit 'New', :class => 'new-button' %>
		</p>

	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoingFirst</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>